enums = ["Other",
         "Ambulance",
         "Beverage",
         "BeveragesVan",
         "Box",
         "BoxTypeDeliveryVan",
         "BoxTypeDeliveryVanHigh",
         "BoxTypeDeliveryVanHighAndLong",
         "BoxTypeDeliveryVanLong",
         "BreakdownTruck",
         "CarCarrier",
         "CattleTruck",
         "CementMixer",
         "ConcretePump",
         "Chassis",
         "DumperTruck",
         "EstateMinibusUpToSeats",
         "FoodCarrier",
         "GlassTransportSuperstructure",
         "GrainTruck",
         "HazardousLoad",
         "HeavyLoad",
         "Horses",
         "HydraulicWorkPlatform",
         "JumboTruck",
         "MiningTruck",
         "RefrigeratorBody",
         "RefrigeratorBox",
         "RefuseTruck",
         "RollOffTipper",
         "SecurityVan",
         "StakeBody",
         "StakeBodyAndTarpaulin",
         "StandardTractorTrailerUnit",
         "SwapChassis",
         "SweepingMachine",
         "TankBody",
         "TankTruck",
         "TimberCarrier",
         "Tipper",
         "ThreeSidedTipper",
         "TrafficConstruction",
         "TruckMountedCrane",
         "VacuumAndPressureVehicle",
         "VolumeTrailer"]
enum_name = "CommercialVehicleCategory"
values = ["Other",
          "Ambulance",
          "Beverage",
          "Beverages van",
          "Box",
          "Box-type delivery van",
          "Box-type delivery van - high",
          "Box-type delivery van - high and long",
          "Box-type delivery van - long",
          "Breakdown truck",
          "Car carrier",
          "Cattle truck",
          "Cement mixer",
          "Concrete Pump",
          "Chassis",
          "Dumper truck",
          "Estate - minibus up to 9 seats",
          "Food Carrier",
          "Glass transport superstructure",
          "Grain Truck",
          "Hazardous load",
          "Heavy load",
          "Horses",
          "Hydraulic work platform",
          "Jumbo Truck",
          "Mining truck",
          "Refrigerator body",
          "Refrigerator Box",
          "Refuse truck",
          "Roll-off tipper",
          "Security van",
          "Stake body",
          "Stake body and tarpaulin",
          "Standard tractor/trailer unit",
          "Swap chassis",
          "Sweeping machine",
          "Tank body",
          "Tank truck",
          "Timber carrier",
          "Tipper",
          "Three-sided Tipper",
          "Traffic construction",
          "Truck-mounted crane",
          "Vacuum and pressure vehicle",
          "Volume trailer"]


def create_cases():
    rs = ""
    for e, v in zip(enums, values):
        rs += '''                case {enum_name}.{enum}:
                    return "{value}"; \n'''.format(enum_name=enum_name, enum=e, value=v)
    print(rs)


create_cases()
